# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blog-api-monitor
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - blog-dev
