---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-registry
  namespace: web-search
spec:
  encryptedData:
    .dockerconfigjson: AgB/yDASkxsXHwlNC+pgp/IPt88W/rqOAPczRWgE1quImDZOQPXbwxy4eM5S7qONT3Sxl+Kes1HsvnaqWF0V+p7s+43jtLw42EHXAv3JqMfxWUWlBITV8/scnysC+g/4XdSBrltkOAD7nzV7DcgWkJDFQ7Un5DVlP6+FHDRuHhh9MJXNPyGrMoHf569hPU+tk+hgr3EMSNyLhhSleE36a5sKUBa0lXB+kgTT0vfPeIBcxlTqq+aZFuPnk2698GzaTZ51e53jzI7sWLx+gxxlid9Aj58h6Y5We1wCh2gauASGEK/7dxD1E/X6lMPG4UmFe7S1Tnw+Bx6yRlJpkDQtepl7/DhtleVfP2+KOS6Aft5ov1mei/pzqQVBAbHVt9PITPNEeHpOvJnvXDKCRDWlk7NVfcRkXWqfq5C0rk+9wwFg1q0ZAzeK2e9pXcEVUz0pAOBFqWhdgGuiz2JyqgoJjQ4o7AB/o+Uge3jxbyM6ulCmvdyThQyvMVtqnrFtimd40vmJk1wBgz+Bj9cJ1U4rxB3+K6aUi6VYRpEf+SrH6XY2yk63Cziu35PNBA1I8bmmrY1vDVuHH/HBuKrA6vS1pwLE8qW8UILblL5kkhBUowDDZz5Y4eXYQfRTExbp0P/0jKP2sKJyEWkEX/tHKiw59J4k6OioDxTwzFmPJKCSY29ng03Qu/OAHzH4wgQh/dC2/m82oyry1bMEluksENhoN+eN9OUhhiZVJwCejuMBBsdK7QrUjPUtK/NqsjbeWyG5LjljTZOeU8bFs+ugiZSxhNPZVlem/KrWE2dNC/mrwx35SxGMUTvHgZEKXt+hIM+yAOAAtZil7wRPKY0BXFU85iOddcF3DVji3/FRkwIjTLNCRWdzpBpf7WtlDIIbjLy74fiek2z6iRXwOZDfOw3YtlRn+UmcFZ7s5eRik0jTQql8AOvvGzGF74PmdumUvSmiYvGVPnPn2zu3Exex
  template:
    metadata:
      name: nexus-registry
      namespace: web-search
    type: kubernetes.io/dockerconfigjson
