---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-registry
  namespace: web-search
spec:
  encryptedData:
    .dockerconfigjson: AgAkTEUTMhkkrGKysz6zJreqGx5RJ4EteldeRxWj6M6bLTTokCDI8xvFQuBL2ePtO8FwDF4IK2iWoO437VgbAUrmavEZvFxZTFI3ADcF8c1QXgYk61X3Gfkxsn1T9gwai+sAg70jVcDIbcyM5kgeEDF5Xid0XIVYoL3JtiNM1lvvfRngDLVAO+MTebjMo+DHk8iGWuOjlcF10vYW8AqQbLyhm0vc3qkLnwKRJrlQgsBAehpfOHtV1yxoG4JebLDsub7ye+vIopklG1kVWfpmJFmjat9TNI3CZ8V9jsZsz2j4nqXHKIhBJqMJrnukO7tXhAmDsLh6pcwg/X6DK93oXoqdTjlCN1Lg3y+tMYyg1t8Hn4wP9wfj+zCV77lTNXGwXDlJ7cmKkAuXA9bDNgx9alnMahnw6ePzgGRb5pafyh1IW6yE+ss3STHBeqrgeJ4D2s4NAgsHeO8uBtsM6gZFpSwipp7vZZV46JghygyzUu+RhIJzxUipyiZC16yBfdFZ01ydzgYmW2aIiIQWK/VP3l4tTMvHxHmUZLe9hqBSd8MstSdTvvC7Wf5u6zZU4k+yvUiwqRcOh4xNbwFCCUjz16x+Vss2E8AuLOTeMKgTCBNE6Nn3sIACy8lZpp4CXemHjk/p4FyztabD30htgidqV5jiLyd594ltgltxSZU8j5sv+WaNpdbOF5auVYg9ZVD2EoMP1eijachsi3+5msP2n8nlXUakld5BTM8mDOwRKQxS6yn5tvA/TrQG1H4tFeE35HvzHD7cdzcoYYSAZGScYfTsPcONb9NZ3RUcLVaXlyzkD2RhjaZWeVTDaO+hP2REMoCASYnQbeJYWa96iBIinTG979kYNU66UwxiiCOEGA==
  template:
    metadata:
      name: nexus-registry
      namespace: web-search
    type: kubernetes.io/dockerconfigjson
