apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    layer: tenant
    release: kube-prom-stack
    tenant: mission-control
  name: notification-service-monitor
  namespace: observability
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - mission-control
  selector:
    matchLabels:
      app: notification-service
