---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets-auth
  namespace: mission-control
spec:
  encryptedData:
    API_AUTH_TOKEN: AgBvbcYY0RsIjHZBbAh7ooYkBJh98hI+nLtdp/UPaPqQXCaBgrfwLYUAzYL06qcDjk24I6XprB/JpusEy8Pa5wJVEuINGTG5pR188qQjAiC5sOHKzMfjpXv58Gy+2QQjMvSfESRtpdG2cF5ae5JB8tseTJ/qZv/IMxpfE++gXPaPnizKFIX+dabNY2usIz2i/kpZbDT6xfENGbSBbN9MODSxgzRGrxy2qCy+qLaEvsp/LaN2eJ+XZK8wiu92fX3TM6SsuA5U+BC6TiZ3R3L/ERJ9Gk2Q/HvUc+o2wTG24vVviBomUOY+D8aAdf8jcaLidRQmpT4i7ack6BkRzjwTlsYFgeKAGcX4UOCIqbj/1L3LvqLganvCfd9xnnGHXu1s79lHkSO1rMhcOFmrhZ6f4Wx183fQT70EoGbGAOKEs6nMOr4Qikn3tcVuwuW1AgozWQpPFV52hKGaIjrUQ8vWTbpcbDoYdiaB5xR040eoxq6/etia7ibC+FsPuxZ63d/jWhWsHxW3SHoHsq0y8eaO6FhvGlE8sUFXzjrPYb1Xx/QMmnCF153/1LO3Rhp6rJLa00JHoqk4LvCpKomT1z8K0TB6wUaV4Qf/JWXTfrbzx+/Bo/fxPx7JxXsG0Gox97eZ8JWfgqZUOu15/yzEbk/Ah5LCxSJUYQkzBKuV0BFpos06VJaQrCe23XYjn4n2HJXuoc3PI94oma8y6c7TSw2h90XExDJ6ERDiyAcQ8NfbF9sosd3B8x428v+qco5DKBpHRkaEUCssHzu1mA4t8iJszmgz
  template:
    metadata:
      name: backend-secrets-auth
      namespace: mission-control
