---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets-auth
  namespace: mission-control
spec:
  encryptedData:
    API_AUTH_TOKEN: AgA8MoDy7+GptjUYeVS711B4YHKrcVGBT9IV7YMYSXgqANt6Cv6KdjU3tq/XfEfE3YfmyKEVpuiyQn/4YiUaWz+TOOgIocaOIm9aTbpdnfI8QxyipPeuE8bw4wqm6varG8oK/O/BvPzCKdB71STeRnMXTcslpKPNk2aEB4INDL6zm9NLcbNYhLBALE78I3Z9iHdOSvkIY8UgnL106vHPS/igtyYLB/ghnZd9EcFNwk0riwn0KKcQvK7bKr/MENJRSR0qqtS+jCSMoIHU1+WpOjD9js9PMrsUMbCq9+pYXlETovRw6n8NeDO7WfNjW+n9rw49gfeLYiJ/3WPHFboRSOHZMPTiBXQDC8ByWCjajbYlNZIBThHIji6P1+pXCdgkuwiOMXvbGnoqQBLkp9rzDbN1+czPTEfnc0kOYUmitMpc6CRgiz3uPy/VS/uAZS+ik1U6KpcW33dq8Hz7r0aRm6CeAIiZf2umqiGoEDryWWA6PWTL4ZSvVyZCFaG3ayZrybOX2jaRFhdjwWlgQbZNnNFnB7AsJqOXqC6NXgb4uGVIUSCrCKXi2pPZ3KfBBXqkUBwYUFWDHI2IJa1ulN2nfsOsSge+fI27r03Ph7Kt67gAUvgMbaPulpGny7FuPy2KrbhjYwFwXZLxdmu8i6e1Ggw5jjgK9NQwvZ0JNmLU6BNR6OxkFuszyPSHXqJuIc8fWUtOoJzXkifENiwGeZmxgl4CvYx361D16orKUd1uEJJgRPzbRpTcItHa9Qxh6ngNJxh+/ENegWUC51CvgTgUY5Cz
  template:
    metadata:
      name: backend-secrets-auth
      namespace: mission-control
