---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets-gemini
  namespace: mission-control
spec:
  encryptedData:
    GEMINI_API_KEY: AgCnx6PuMBA0VdTIKt/LRHWu5i1oOo+r6q6pU36jNqRWBosQByGkPA4F7wc6Oxi1WOo6Gxvh2fQiLqOlni0S1SBevPbmBriJNAnqR+Jvf1PKv4+dwoIkdqTPImQFNW7OBt5uLXmRyOrH4mNbp3TPGNrlswcBZGD+LFr/4cd2J+DiFeXN1Iii5VGSK5n0L2P8BTWt4sjsUSnY1zzFuwK5rDJnaNnVMDieoYlirfLuERzhxqPkgz7Sa4c44ZAt2X8iWxzPFd/YCInlxaa+7MAwXXrHF27kMLjVK2jc7wHRfOV0MwaS7liYVeb5TVCkX9ZLswtRUs5EXE5zW66CZPa65q9bWpK7Rb28zNaWy0vbIfoOES/waHu6Z28hLCTlu8Nmr4Db0wldFi8gshz7PJYCuJg85eFm7iv9Y6pS/Lv7pmfwP5vk2Fxqx1YuCJAw80mPsRLX5ssIdaA6GK10jh+a8wQpNSjgrjGH22s1q4ZK+D2vlXyOYjDd1IAH1TozRQfn4iDktLLEBQE6eDQocZUqJoUh+WD3fT/HaLvkb3xLTEetAvqDutBpCAv1sVcO8SNc7vsW2Jg5iyH0F0jyrPcNsGFUIeZ+wl8ZomlIi+9tM0wtNfEhmMLGqeubOQ1IqkgnmJvNiHUXuu/OOkh7Em00Lf3am8sMwu8jAE7m+rkFkyx8N4PqD7UIpn1sqkckA0T4uI8lP5jh9+vzi/FtRaKN2GapD/C7TV9/5miowPhZJjx8OInXCSJgMy8=
  template:
    metadata:
      name: backend-secrets-gemini
      namespace: mission-control
