---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets-postgres
  namespace: mission-control
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCmGJxYCeIvbrTjdIxvwBfSBuYIoVh2g/FzAeIibOs/Zp74w84tsoC9qxTeIxlfAdDzO9eXCYOkYB0Re8SqabMR33JNKBZCKqsSZBtedQwwOaSSfTuhGzHO4b0JZAgCwO38X46sbhG8JfjsIrN7WWn5cm9VSc0rKSUOyoipgCUufkABjUcP6C0lPCQkAuMRHsGz+hzwBKVkve9UxTXPJNLGlhfsat/AGZ2JR81T7bjP12W7GrLzaZGD32uaFOlrW9G2/K9NgCEIy6bP0eO/aG2xHEJ+wb/J4FAhyxh9JeFNg2E6uF11r9YGF03zQ33MCcWk6plwRVBwUXamsdS4ZDYSMqi6RRY28GJHmI/J+0sNfumicuFwaP9zMfTyrIT20mTZetEooQJpK8M0/pJnZtJnt0aP3ZPWVl7UJPpNgfGj7PBT3eabpDfG1wirjr7dozhbw+sAp6ZLo4tnm8CyJqfh6pm8/94RQ6B+iNBhYaC4NWXsoS7H4ehbYxdH+NT67sbVW/u15DymO6UXx/1KzoVDMRVRVwncnqsllcfjdrjwmaUKRT311SmCE1ZUOeX+ebVRMyOlR2m3N375rv8OW4RT10xiGU/5kt7My3rT4o+ISDudy608phe3CnrVW4YbL5kgDfIRuvqWY28EazxbvoQ9KYMDiVJbaMVBymDHfnL5pO5Ik7n3Nxkk916OEpcSEwYQj92oGlufCS47ALxPAg9E1VFslnVULsoynhvKAzZ8c4ldfgyxdubbdX+s8Q==
  template:
    metadata:
      name: backend-secrets-postgres
      namespace: mission-control
