---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets-postgres
  namespace: mission-control
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCbEf7ivlU7UHQ1aMgKQD/rWhC84z8jVL8nmMLi01qW4Dbfzpxr0xsVIak2aZJen9MLW4z5+rTEwqxtgfj0Pvn2OrLZOsWkHFxG2BrcIeBTN+XW6c8CgPNjoN7eeCmYjByF7pyc0oEwo/af4F8iC9NXMryzpzED934fAodKdZ4r+YXiZPRG6O7Gcw37muGpf4RbXqt8InPE+OQO0VbnNturVCLdTbr9SSGtY3kxljHmTS2KLnteaaR9jUleS3FlQRCdibha52g6JCxgujw/cgQEbkgqnp+KQhoA0Q8MOTQDPvXNglusRyEiGjvM945gNVq7pqP8r8rU51eFFRGuld9XhrtMn7IY1rTGMY1ptoFCg1C6rthFIQLeyH8MUmVMKxfcving6j53o3EbK/nt02EczAymWTy7q011Jfqtm4+2gj8cDSdsi9IuAVlXFSCDc6R3a1C2TiLhK46gYYPhGTNuxKmaPg5Fb0+125D2UmzD4KmrNto5zy+Jnht11hqwq6imHTjZDbLOv5/+UmLHDqP9DGtXHk+KuZ3XOQUQXKn3fhyEm8NFf/NZlckf4E5yf5cKnMeLR2+WUJ3aCefrqVwC2ShMOR45nXHiEgxSlowee9/J/al4KqzfsWcFv/QE+ohlWs1IYq4sbDGYwsSoFC3NEuWqq+nVYwL8KMTVIKnCmVHexybypeZXQ/VQgUcyJ3VUHmtiWST2JFo4Dx86GwdHqtue/Lk5U5Ly76d/Xnm0vHsYKcx0Ol35UI/mbA==
  template:
    metadata:
      name: backend-secrets-postgres
      namespace: mission-control
