---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets-proxmox
  namespace: mission-control
spec:
  encryptedData:
    PROXMOX_API_TOKEN: AgB2OUEq31tzlEidiOc7QQyY/fYvks17E8FbD32VNNLG/89KN/hUxJ9Q2Z+BsbRkiRQkP0w/h//iMLksO5nFKI32fqJFwgeB+lsEXZ9LLtIWTWCEXqSYXupnqM5HOirqv2ni0AwG3MXWa3p4apWnSA56SuttYadPOeN1G+0uTjjNwCqq5j+Ox08+p0iTdt8U73gd4yszT55eKHrSRqVBCGPmxteI83VCnbVfepCsP9CoNhp6uXEJ8KniTkLCZfzT4nKpOdqEYHO4NLOrLTCz90au30ZHtdKe35nK2a7L4Y8FnewoQSDzh4ZUbAuTV3jY4eFdZWVozfvmMqqJrTexXnC1bZYWapHMTk0cOPZ9HtOb4B2GangBVP7AiHznK0EBzGIEb9HMCSrC47g37ykZ/nCwooecwUHcuFvKl38oQjojYAPOGSav8x4u7lmyQpwZEru9xXv5zswtv+Sj20ojt+/yDXhm6JbQxAJ5EgnXSpgTngMT31PN62ueW+pYO0F6idFRxBnDSBKifRCE0O3MeQDhekd8H9m1JM6JUJFlkUIkKuOuuxStvHiX6O/Ce2KKIeIiGX1nm9SSqyW/bKVwDVceRPxVMNgDAAAmwCcqv8hRFwgc4ROyOaT1HC4ZLFaWlTnEdUfoiJbg4L9S81HOk+v1IvOnv739HR8KQkQVWfKNLI3y+PQ9JB5qH6xmZfANrRK8wcvGRQnCJCQGRIZkaUnodqJkMgS60P5EVgLljJxuoguL1aPcmM0+t8NKz4qc0zXFU9TEifsK0+qRRr00H1Q2
  template:
    metadata:
      name: backend-secrets-proxmox
      namespace: mission-control
