---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets-proxmox
  namespace: mission-control
spec:
  encryptedData:
    PROXMOX_API_TOKEN: AgCFC2OTVca2FHTHDYOBYG4EKIyDAskCLCRPLu3bAzcka4AIA/BqdpTlGpciu0UzH159Ux1ndvHSV2K4OS83UeEcGrv80SC/dcJTrUnqAN/YYjBBiveiErNM5w5FoE9dD5cNUXuQBPFJClBj+o7Vf0W1dWEQq2SzXVzBVQ90AIKI7wC5l2eKClapbCMijA+j+z9SXYjqdDvQpHZn/+g+DWxjGMBCIXIXLW/jRqokYLSK/MniXU4yUe24CuZgburnYcWZsPRxCzeGVAWa3tPDaLFPnmp070ZvQBb8PhelHWCpeJdadX/hH88iTFdAxdxKGPvKTt0MFlCOo+JoNXpSkZH5O9xI6GhLGjinRtxWA7FCPyqXZs9lMDtQVuDeR5yLMxbR6kPT/xamq1TTaJtYTFuxXpaA0TTd/rfdqG3bc9a8leDyWbKCMG9fPWVJ7nEK449AikN80Fgz54sEmpJPOF1tSCKFY8WuTIHT6os2BwYGIJYCWKxcouw+CfxA2gzcHkN/7Zote/hfD1awhtlztJsPUarNqeIHWVri20xE6dGcp6VIrvwCHe8qAsZx8ra+WieysAbJZHTva9Vny9ttvWX0lffUWP4hTJ+w19vhmDz/MPBM3xuzF3z+uvfvBkdnixjF2NPnWrAmty9HRS5vEEE/bgH7765WW5ajNOIMw5OcMmLm3mygeupzj8BDpU0nucmRHcRecXKl5fk0NjbfOVFKWquYFYxpZuDsox3T7YP7HTlIObBo9ApIkL0Po11jX1CgBaWIsQ7hYLPrrUJGGZlv
  template:
    metadata:
      name: backend-secrets-proxmox
      namespace: mission-control
