apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-observability-stage
  namespace: argocd
  labels:
    layer: tenant
    tenant: blog
    environment: stage
spec:
  project: petedillo-stage
  source:
    repoURL: https://github.com/petedillo/blog-gitops
    targetRevision: HEAD
    path: homelab/infra/gitops/blog-observability/overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
