apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-observability
  namespace: argocd
  labels:
    layer: tenant
    tenant: blog
spec:
  project: default
  source:
    repoURL: https://github.com/petedillo/homelab-gitops
    targetRevision: HEAD
    path: blog-observability/base
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
