apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-bot-observability
  namespace: argocd
  labels:
    layer: tenant
    tenant: discord-bot
    environment: prod
spec:
  project: default
  source:
    repoURL: https://github.com/petedillo/homelab-gitops
    targetRevision: HEAD
    path: discord-bot-observability/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
