apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-stack
  namespace: argocd
  labels:
    layer: platform
spec:
  project: default
  source:
    repoURL: https://github.com/petedillo/blog-gitops
    targetRevision: HEAD
    path: homelab/infra/gitops/observability-stack/base
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
