apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-search-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: websearch=docker.pdlab.dev/web-search-service:latest
    argocd-image-updater.argoproj.io/websearch.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/PeteDio-Labs/petedio-labs-gitops
    targetRevision: main
    path: web-search-service/base
  destination:
    server: https://kubernetes.default.svc
    namespace: web-search
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
