apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blog-api-monitor
  namespace: observability
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: blog-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
