apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pete-bot-monitor
  namespace: observability
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: pete-bot
  namespaceSelector:
    matchNames:
      - pete-bot
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
